"""initial tables

Revision ID: c70af81ea8f2
Revises: 
Create Date: 2026-01-07 17:19:17.209817
"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = 'c70af81ea8f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.String(length=255), nullable=False),
    sa.Column('results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cached_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cached_requests')
    op.drop_table('area_lookups')
    # ### end Alembic commands ###
